# config/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: 'microservice'
    static_configs:
      - targets: ['microservice:8070']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
#    labels:
#      application: 'esempio04-microservice'
#      environment: 'docker'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']