# kubectl logs -n kafka -l app=kafka --previous
# kubectl logs -p kafka-fdcb9cc57-slrcf --namespace=gestioneannotazioni

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-service
  namespace: gestioneannotazioni
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-service
  template:
    metadata:
      labels:
        app: kafka-service
    spec:
      containers:
        - name: kafka-service
          #image: confluentinc/cp-kafka:8.1.0
          image: confluentinc/cp-kafka:7.5.0
          env:
          - name: "KAFKA_CLUSTER_ID"
            value: "LkX5j6kRSaO-0a4b9b3c8-9d6e-4f4e-8f4e-8f4e8f4e8f4e"
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper:2181"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: LISTENER_INTERNAL://kafka-service:9092,LISTENER_EXTERNAL://localhost:9093
            #value: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://kafka:29092"            
          - name: KAFKA_LISTENERS
            value: LISTENER_INTERNAL://0.0.0.0:9092,LISTENER_EXTERNAL://0.0.0.0:9093
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: LISTENER_INTERNAL
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "true"

          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          ports:
            - containerPort: 9092
              name: plaintext
            - containerPort: 29092
              name: internal
          
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 15
          
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 15
            failureThreshold: 6
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1000m"

---
apiVersion: v1 # Kafka Service
kind: Service
metadata:
  name: kafka-service
  namespace: gestioneannotazioni
spec:
  type: NodePort
  ports:
    - name: kafka-plaintext
      port: 9092
      targetPort: 9092
      nodePort: 30092
    - name: kafka-internal
      port: 29092
      targetPort: 29092
      nodePort: 30029
  selector:
    app: kafka-service

