apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:1.0.0
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: demo
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: demo
            - name: ME_CONFIG_MONGODB_URL
              value: mongodb://demo:demo@mongo:27017/
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: demo
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: demo
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30082
  selector:
    app: mongo-express
