# Configurazione server
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /

# Configurazione applicazione Spring Boot
spring:
  application:
    name: sistema-gestione-annotazioni
  
  profiles:
    active: onprem

  # Configurazione Web
  web:
    resources:
      static-locations: classpath:/static/

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          github:
            client-id: ${GITHUB_CLIENT_ID:your-github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:your-github-client-secret}
            scope: read:user,user:email
          microsoft:
            client-id: ${MICROSOFT_CLIENT_ID:your-microsoft-client-id}
            client-secret: ${MICROSOFT_CLIENT_SECRET:your-microsoft-client-secret}
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/v1.0/me
            user-name-attribute: id

# Configurazione Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      processor: false

# Configurazione logging
logging:
  level:
    it.alnao.springbootexample: INFO
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Configurazione personalizzata
gestione-annotazioni:
  config:
    max-annotation-size: 10000
    max-description-size: 500
    default-priority: 2
    enable-public-annotations: true
  nosql:
    annotazioni-table-name: ${ANNOTAZIONI_TABLE:annotazioni}
    annotazioni-storico-table-name: ${ANNOTAZIONI_STORICO_TABLE:annotazioni_storico}
  sql: #see CustomPhysicalNamingStrategy
    annotazioni-metadata-table-name: ${ANNOTAZIONI_METADATA_TABLE:annotazioni_metadata}
    users-table-name: ${USERS_TABLE:users}
    user-providers-table-name: ${USER_PROVIDERS_TABLE:user_providers}
    refresh-tokens-table-name: ${REFRESH_TOKENS_TABLE:refresh_tokens}
  # Configurazioni JWT aggiuntive 
  jwt:
    secret: ${JWT_SECRET:myVeryLongSecretKeyForHS512ThatMustBeAtLeast512BitsLongToWorkProperly1234567890abcdefghijklmnopqrstuvwxyz}
    expiration: ${JWT_EXPIRATION:86400} # 24 ore in secondi
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800} # 7 giorni in secondi
    # Configurazioni CORS
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:8080
      - http://localhost:8081
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    allow-credentials: true
  export-annotazioni:
    enabled: true
    cron-expression: "0 0 0 * * *"   # ogni giorno a mezzanotte
