# Configurazione profilo aws - MySQL + DynamoDB + SQS
spring:
  # Configurazione database MySQL/RDS
  datasource:
    url: ${AWS_RDS_URL:jdbc:mysql://localhost:3306/gestione_annotazioni}
    username: ${AWS_RDS_USERNAME:admin}
    password: ${AWS_RDS_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # Configurazione JPA per MySQL
  jpa:
    packages-to-scan: 
      - it.alnao.springbootexample.aws.entity
      - it.alnao.springbootexample.aws.entity.auth
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        '[format_sql]': true
        '[physical_naming_strategy]': it.alnao.springbootexample.core.config.CustomPhysicalNamingStrategy

  # Disabilita MongoDB per il profilo aws e disabilita azure per profilo aws
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.cosmos.CosmosAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.cosmos.AzureCosmosAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.context.AzureContextAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.context.AzureTokenCredentialAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.kafka.AzureEventHubsKafkaOAuth2AutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.AzureGlobalPropertiesAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.storage.AzureStorageBlobAutoConfiguration
      - com.azure.spring.cloud.autoconfigure.implementation.storage.AzureStorageQueueAutoConfiguration

# Configurazione DynamoDB
aws:
  region: ${AWS_REGION:eu-west-1}
  access-key: ${AWS_ACCESS_KEY_ID:}
  secret-key: ${AWS_SECRET_ACCESS_KEY:}
  dynamodb:
    annotazioni-table-name: ${DYNAMODB_ANNOTAZIONI_TABLE_NAME:annotazioni}
    endpoint: ${DYNAMODB_ENDPOINT:}
  sqs:
    endpoint: ${SQS_ENDPOINT:}
    queue-url: ${SQS_QUEUE_URL:}

# Configurazione export annotazioni via SQS
gestione-annotazioni:
  export-annotazioni:
    enabled: true
    cron-expression: "0 */5 * * * *"  # ogni 5 minuti

