spring:
  profiles:
    active: azure
  cloud:
    azure:
      cosmos:
        endpoint: ${YOUR_COSMOS_ENDPOINT:localhost}
        key: ${YOUR_COSMOS_KEY:localKey}
        database: ${YOUR_COSMOS_DATABASE:localDatabase}
        populate-query-metrics: true
  datasource:
    url: jdbc:sqlserver://${YOUR_SQLSERVER_HOST:localhost}:1433;databaseName=${YOUR_DB:localDB};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ${YOUR_SQLSERVER_USER:localUser}
    password: ${YOUR_SQLSERVER_PASSWORD:localPassword}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
