version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8047:8047"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      - db
    networks:
      - es07-mynetwork

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - es07-db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Espone la porta di PostgreSQL (opzionale, utile per accedere con un client esterno)
    networks:
      - es07-mynetwork

volumes:
  es07-db_data:

networks:
  es07-mynetwork:
    driver: bridge