version: "3.8"

services:
  # Database per SonarQube
  db:
    image: postgres:13
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - sonarqube_data:/var/lib/postgresql/data
    networks:
      - sonarqube-network
    restart: always

  # Server SonarQube
  sonarqube:
    image: sonarqube:lts # Usa la versione Long Term Support
    container_name: sonarqube-server
    depends_on:
      - db
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000" # Porta per l'interfaccia web di SonarQube
      - "9001:9001" # Porta per il SonarQube Scanner (se necessario, altrimenti può essere omessa)
    volumes:
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks:
      - sonarqube-network
    restart: always

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:

networks:
  sonarqube-network: