server:
  port: 8080
spring:
  application:
    name: esempio04dbNoSql
  profiles:
    active: local
  data:
    mongodb:
#      host: ${MONGO_HOST:localhost}
#      port: ${MONGO_PORT:27017}
#      database: ${MONGO_DB_NAME:microservice_db}
#      username: ${MONGO_USERNAME:}
#      password: ${MONGO_PASSWORD:}
#      authentication-database: admin
# sistema per avere il authSource=admin con uri ma non mi piaced
      uri: mongodb://${MONGO_USERNAME:}:${MONGO_PASSWORD:}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB_NAME:microservice_db}?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  server:
    port: 8080  # Se vuoi che actuator usi la stessa porta dell'app

aws:
  region: ${AWS_REGION:eu-central-1}
  dynamodb:
    endpoint: ${DYNAMODB_ENDPOINT:}
    tableName: users
  accessKey: ${AWS_ACCESS_KEY:local}
  secretKey: ${AWS_SECRET_KEY:local}

#app:
#  database:
#    type: ${DATABASE_TYPE:dynamo}

logging:
  level:
    '[it.alnao.esempio04]': DEBUG
    software.amazon.awssdk: INFO
