apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  default.conf: |
    server {
        listen 8042;

        location /api/ {
            proxy_pass http://springboot-app:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-bootstrap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-bootstrap
  template:
    metadata:
      labels:
        app: frontend-bootstrap
    spec:
      containers:
        - name: frontend
          image: alnao/j-esempio02-frontend-bootstrap
          ports:
            - containerPort: 80
          env:
            - name: API_URL
              value: "http://63.177.240.41:31083"
              #value: "http://localhost:43797"  #senza barra finale
              #qui si usa la 8080 perchè è il frontend che deve arrivare al backend
        - name: nginx-proxy
          image: nginx:latest
          ports:
            - containerPort: 8042 # ✅ Porta cambiata per evitare conflitto
          volumeMounts:
            - name: shared-assets
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-config #nginx-proxy-config  
        # Volume condiviso tra frontend e nginx-proxy
        - name: shared-assets
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-bootstrap
spec:
  type: LoadBalancer
  selector:
    app: frontend-bootstrap
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80   # ✅ TargetPort punta alla porta 80 del container nginx-proxy
      nodePort: 31082       # Porta esterna (sul nodo) per l'accesso dall'esterno
      name: http
    - protocol: TCP
      port: 8042
      targetPort: 8042   # ✅ TargetPort punta alla porta 80 del container nginx-proxy
      nodePort: 31083       # Porta esterna (sul nodo) per l'accesso dall'esterno
      name: proxy