apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-app
spec:
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
        - name: mysql-app
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "alnaoMeraviglioso"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  selector:
    app: mysql-app
  ports:
    - protocol: TCP
      port: 3306       # Porta interna del Service (accesso interno al cluster)
      targetPort: 3306 # Porta del container dove arriva il traffico
      nodePort: 30307   # Porta esterna (sul nodo) per l'accesso dall'esterno
