apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: alnao/j-esempio02-backend-springboot
          env:
            - name: MYSQL_PORT
              value: "3306" #qui non si usa la 30307 perchè è il container che deve arrivare al mysql
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_ROOT_PASSWORD
              value: "alnaoMeraviglioso"
            - name: CUSTOM_MESSAGE
              value: "Sono un messaggio custom dall'ambiente"
          ports:
            - containerPort: 8080
            
      dnsPolicy: "ClusterFirst"
#      dnsConfig:
#        nameservers:
#          - 192.168.49.1
#          - 8.8.8.8
#        searches:
#          - default.svc.cluster.local
#          - svc.cluster.local
#          - cluster.local
#        options:
#          - name: ndots
#            value: "5"

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-app
spec:
  type: LoadBalancer
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 8080           # Porta interna del Service (usata nel cluster)
      targetPort: 8080     # Porta del container dove arriva il traffico
      nodePort: 31081       # Porta esterna (sul nodo) per l'accesso dall'esterno