version: '3.8'

services:
  # MySQL per simulare RDS
  mysql:
    image: mysql:8.0
    container_name: gestioneannotazioni-mysql
    environment:
      MYSQL_DATABASE: gestioneannotazioni
      MYSQL_USER: gestioneannotazioni_user
      MYSQL_PASSWORD: gestioneannotazioni_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3406:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../init-database/init-mysql.sql:/docker-entrypoint-initdb.d/init-mysql.sql:ro
    networks:
      - aws-kube-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # DynamoDB local
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: gestioneannotazioni-dynamodb
    user: root
#    working_dir: /home/albertonao/
    ports:
      - "8420:8000"
    networks:
      - aws-kube-network
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data

  localstack: #per SQS in locale!
    image: localstack/localstack:3
    container_name: gestioneannotazioni-localstack
    ports:
      - "4566:4566"  # endpoint unico per tutti i servizi AWS locali
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=eu-central-1
    networks:
      - aws-kube-network
    volumes:
      - ./localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localstack:4566/_localstack/health"] #ex http://localhost:4566/health
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    # awslocal sqs create-queue --queue-name annotazioni
    # docker exec -it gestioneannotazioni-localstack awslocal sqs list-queues
  init-sqs: #questo crea la coda SQS in Localstack
    image: amazon/aws-cli
    container_name: gestioneannotazioni-init-sqs
    entrypoint: ["/bin/sh", "-c", "until curl -sf http://localstack:4566/_localstack/health; do echo 'Waiting for LocalStack...'; sleep 3; done; aws sqs create-queue --queue-name annotazioni --endpoint-url=http://localstack:4566 --region=eu-central-1"]
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=eu-central-1
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - aws-kube-network
    restart: "no"

  # Applicazione Spring Boot profilo AWS
  app:
    image: alnao/gestioneannotazioni:latest
    container_name: gestioneannotazioni-app-aws
    environment:
      SPRING_PROFILES_ACTIVE: aws
      SERVER_PORT: 8085
      # Database MySQL/RDS
      AWS_RDS_URL: jdbc:mysql://mysql:3306/gestioneannotazioni
      AWS_RDS_USERNAME: gestioneannotazioni_user
      AWS_RDS_PASSWORD: gestioneannotazioni_pass
      # Credenziali AWS (CORRETTE per AWS SDK v2)
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      AWS_REGION: eu-central-1
      # DynamoDB
      DYNAMODB_ENDPOINT: http://dynamodb:8000
      DYNAMODB_ANNOTAZIONI_TABLE_NAME: annotazioni
      # SQS LocalStack
      SQS_ENDPOINT: http://localstack:4566
      SQS_QUEUE_URL: http://localstack:4566/000000000000/annotazioni
      SQS_REGION: eu-central-1
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
      dynamodb:
        condition: service_started
    networks:
      - aws-kube-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Adminer per MySQL
  adminer:
    image: adminer:4.8.1
    container_name: gestioneannotazioni-adminer-aws
    ports:
      - "8086:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - aws-kube-network

  # DynamoDB Admin UI
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: gestioneannotazioni-dynamodb-admin
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    ports:
      - "8087:8001"
    depends_on:
      - dynamodb
    networks:
      - aws-kube-network

  # Servizio one-shot per inizializzazione tabella DynamoDB
  init-dynamodb:
    image: amazon/aws-cli
    container_name: gestioneannotazioni-init-dynamodb
    entrypoint: ["/bin/sh", "-c", "/init-database/init-dynamodb.sh"]
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    volumes:
      - ../init-database/init-dynamodb.sh:/init-database/init-dynamodb.sh:ro
    depends_on:
      - dynamodb
    networks:
      - aws-kube-network
    restart: "no"

# Nginx reverse proxy per frontend statico e API
 # nginx:
 #   image: nginx:1.25
 #   container_name: gestioneannotazioni-nginx
 #   ports:
 #     - "8080:80"
 #   volumes:
 #     - ../..//adapter-web/src/main/resources/static:/usr/share/nginx/html:ro
 #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
 #   depends_on:
 #     - app
 #   networks:
 #     - aws-kube-network

volumes:
  mysql_data:
    driver: local
  # dynamodb_data volume non più necessario, ora si usa una directory locale

networks:
  aws-kube-network:
    driver: bridge


