# In Esempio03dbDockerAWS-backend/buildspec.yml
version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17 # Ensure this matches your Java version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image for backend...
      - mvn clean install -DskipTests # Build Spring Boot JAR
      - docker build -t $ECR_REPOSITORY_URI_BACKEND:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY_URI_BACKEND:$IMAGE_TAG $ECR_REPOSITORY_URI_BACKEND:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPOSITORY_URI_BACKEND:$IMAGE_TAG
      - printf '[{"name":"backend-container","imageUri":"%s"}]' "$ECR_REPOSITORY_URI_BACKEND:$IMAGE_TAG" > imageDetail.json
artifacts:
  files:
    - imageDetail.json
  base-directory: . # Output artifact from the current directory