server:
  port: 8047

spring:
  application:
    name: microservice-esempio07
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/esempio07_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
# Per creare le tue tabelle ("contenuti" e "users") hai diverse opzioni, che sono tipiche delle applicazioni Spring Boot che usano un database:
# Hibernate/JPA con ddl-auto (scelta più comune e semplice per lo sviluppo):
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
  
  security:
    jwt:
      secret: mySecretKey1234567890alnaoBellissimo
      expiration: 86400000 # 24 ore in millisecondi

logging:
  level:
    it.alnao.esempio07: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE